[package]

name = "rustertest"
version = "0.0.1"
authors = ["Daniel Goertzen <daniel.goertzen@gmail.com>"]

[lib]
name = "rustertest"
#crate-type = ["dylib"]
crate-type = ["staticlib"]


[dependencies.ruster]
path = "../ruster"
